"use client";

import Link from "next/link";
import React from "react";
import { RepoCard } from "@/components/RepoCard";
import { MarkdownViewer } from "@/components/MarkdownViewer";
import { Lightbulb } from "lucide-react";
import { HealthScore } from "@/components/HealthScore";
import { ComplexityBadge } from "@/components/ComplexityBadge";
import { DependencyGrid } from "@/components/DependencyGrid";
import { LearningPath } from "@/components/LearningPath";
import { InterviewQuestions } from "@/components/InterviewQuestions";
import { ExportMenu } from "@/components/ExportMenu";
import { MermaidViewer } from "@/components/MermaidViewer";
import { motion } from "framer-motion";
import { RepoInfo, ReportContent } from "@/lib/types";

export function ReportDashboard({ data }: { data: { info: RepoInfo; report: ReportContent } }) {
  if (!data) return null;

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring" as const, stiffness: 300, damping: 24 } }
  };

  return (
    <motion.div 
      variants={container} 
      initial="hidden" 
      animate="show" 
      className="container mx-auto px-4 max-w-7xl py-12 space-y-6"
    >
      {/* Header Row */}
      <motion.div variants={item} className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8 print:mb-4">
        <div>
          <h1 className="text-3xl font-bold">Repository Analytics Dashboard</h1>
          <p className="text-muted-foreground">Comprehensive insights generated by AI</p>
        </div>
        <div className="flex flex-wrap items-center gap-3">
          <Link href="/" className="px-4 py-2 bg-primary/10 text-primary rounded-lg font-medium hover:bg-primary/20 transition-colors text-sm flex items-center gap-2">
            New Analysis
          </Link>
          <ExportMenu data={data} />
        </div>
      </motion.div>

      {/* Top Section - Overview & Health */}
      <div className="grid lg:grid-cols-3 gap-6">
        <motion.div variants={item} className="lg:col-span-2">
          <RepoCard info={data.info} />
        </motion.div>
        <motion.div variants={item} className="lg:col-span-1">
          <HealthScore score={data.report.healthScore} />
        </motion.div>
      </div>

      {/* Middle Section - Complexity & Path */}
      <div className="grid lg:grid-cols-4 gap-6">
        <motion.div variants={item} className="lg:col-span-1">
          <ComplexityBadge 
            level={data.report.complexity?.level} 
            explanation={data.report.complexity?.explanation} 
          />
        </motion.div>
        <motion.div variants={item} className="lg:col-span-2">
          <DependencyGrid dependencies={data.report.dependencies} />
        </motion.div>
        <motion.div variants={item} className="lg:col-span-1">
          <LearningPath path={data.report.learningPath} />
        </motion.div>
      </div>

      {/* Architecture Section */}
      {data.report.mermaidDiagram && (
        <motion.div variants={item} className="glass rounded-2xl p-8 border border-border/50 shadow-sm bg-card/50 print:break-inside-avoid">
          <h3 className="text-2xl font-bold mb-6">Architecture Diagram</h3>
          <MermaidViewer chart={data.report.mermaidDiagram} />
        </motion.div>
      )}

      {/* Bottom Section - Improvements & Interview */}
      <div className="grid lg:grid-cols-2 gap-6">
        <motion.div variants={item} className="glass rounded-2xl p-6 border border-border/50 shadow-sm print:break-inside-avoid">
          <h3 className="text-lg font-semibold mb-6 flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-amber-500" />
            Suggested Improvements
          </h3>
          <ul className="space-y-3">
            {data.report.improvements?.map((imp: string, i: number) => (
              <li key={i} className="flex gap-3 text-sm">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-500 shrink-0 mt-1.5" />
                <span>{imp}</span>
              </li>
            ))}
          </ul>
        </motion.div>
        
        <motion.div variants={item} className="print:break-inside-avoid">
          <InterviewQuestions questions={data.report.interviewQuestions} />
        </motion.div>
      </div>

      {/* Raw Markdown Fallback */}
      <motion.div variants={item} className="glass rounded-2xl p-8 border border-border/50 shadow-sm bg-card/50 print:break-before-page">
        <h3 className="text-2xl font-bold mb-6 pb-4 border-b border-border/50">Full AI Report</h3>
        <MarkdownViewer content={data.report.rawMarkdown} />
      </motion.div>

    </motion.div>
  );
}
